# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Fetch yarn for backend
      run: yarn
      working-directory: ./backend
    - name: Build backend
      run: yarn tsc --noEmit
      working-directory: ./backend
    - name: Fetch yarn for frontend
      run: yarn
      working-directory: ./
    - name: Build frontend
      run: yarn build
      working-directory: ./frontend
